# Generated by Django 3.2.4 on 2021-06-25 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', editable=False, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'P'), ('active', 'A'), ('resolved', 'R'), ('closed', 'C')], default='pending', help_text='Update the Status to Closed after 72 hours', max_length=10)),
                ('isp_provider', models.CharField(default='Bell', max_length=45)),
                ('issue_type', models.CharField(default='No Sync', max_length=45)),
                ('service_area', models.CharField(default='Location in Splunk', max_length=45)),
                ('ccp_account_reference', models.CharField(blank=True, default='101444777', max_length=60)),
                ('start_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Use EST Timezone')),
                ('etr', models.CharField(blank=True, default='NO ETR', max_length=60)),
                ('ticket_number', models.CharField(blank=True, default='BR number', max_length=20)),
                ('impact_level', models.CharField(blank=True, choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=1)),
                ('notes', models.TextField(blank=True, default='none', max_length=150)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
